language: cpp
dist: trusty
sudo: required
osx_image: xcode7.3
branches:
  only:
    - master

matrix:
 include:
   - os: osx

before_script:
  - source scripts/travis/prerequisites.sh

script:
  - ls -al
  - cd scripts && python swigpp-objc.py
  - cd scripts && python build-ios.py --ios-arch=arm64
