branches:
  only:
    - master

matrix:
 include:
   - os: osx
     sudo: required
     language: cpp
     osx_image: xcode7.3

   - os: linux
     sudo: required
     dist: trusty
     language: android
     android:
       components
         - tools
         - platform-tools
         - build-tools-23.0.2
         - android-10
         - android-21


before_script:
  - source scripts/travis/prerequisites.sh

script:
  - source scripts/travis/build.sh
