branches:
  only:
    - master

os: linux
sudo: required
dist: trusty
language: android

android:
  components:
    - build-tools-23.0.2
    - android-10
    - android-21

before_script:
  - source scripts/travis/prerequisites.sh

script:
  - source scripts/travis/build.sh
