branches:
  only:
    - master

android:
  components:
    - build-tools-23.0.2
    - android-11
    - android-21
  licenses:
    - android-sdk-license-.+
    - '.+'

matrix:
 include:
   - os: osx
     osx_image: xcode12.5
     language: cpp

   - os: linux
     dist: bionic
     language: android

before_script:
  - source scripts/travis/prerequisites.sh

script:
  - source scripts/travis/build.sh
