#pragma once

namespace routing {

    namespace RoutingAction {
        enum RoutingAction {
            ROUTING_ACTION_HEAD_ON,
            ROUTING_ACTION_FINISH,
            ROUTING_ACTION_NO_TURN,
            ROUTING_ACTION_GO_STRAIGHT,
            ROUTING_ACTION_TURN_RIGHT,
            ROUTING_ACTION_UTURN,
            ROUTING_ACTION_TURN_LEFT,
            ROUTING_ACTION_REACH_VIA_LOCATION,
            ROUTING_ACTION_ENTER_ROUNDABOUT,
            ROUTING_ACTION_LEAVE_ROUNDABOUT,
            ROUTING_ACTION_STAY_ON_ROUNDABOUT,
            ROUTING_ACTION_START_AT_END_OF_STREET,
            ROUTING_ACTION_ENTER_AGAINST_ALLOWED_DIRECTION,
            ROUTING_ACTION_LEAVE_AGAINST_ALLOWED_DIRECTION,
            ROUTING_ACTION_GO_UP,
            ROUTING_ACTION_GO_DOWN,
            ROUTING_ACTION_WAIT,
            ROUTING_ACTION_ENTER_FERRY,
            ROUTING_ACTION_LEAVE_FERRY
        };
    }

} // namespace routing
