// @ts-check

/**
 * The sidebar is generated from the docs/ folder structure. Ordering and
 * category labels come from each folder's _category_.json and per-file
 * `sidebar_position` frontmatter.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
